# -*- coding: utf-8 -*-
"""student

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmhHp9aR_RI-ivXojj0x9khIp4aki6j4
"""

import streamlit as st
import numpy as np
import joblib

# Load the trained model
model = joblib.load("stu.pkl")

# Set page config
st.set_page_config(
    page_title="🎓 Student Performance Predictor",
    page_icon="📈",
    layout="centered"
)

# Custom CSS for polished look
st.markdown("""
    <style>
        .main {background-color: #f5f7fa;}
        .title {
            font-size: 36px;
            font-weight: 700;
            color: #1f4e79;
            margin-bottom: 20px;
        }
        .subtitle {
            font-size: 20px;
            font-weight: 400;
            color: #3d3d3d;
        }
        .stButton>button {
            background-color: #1f4e79;
            color: white;
            border-radius: 8px;
            padding: 10px 20px;
        }
        .stButton>button:hover {
            background-color: #155d8b;
        }
    </style>
""", unsafe_allow_html=True)

# Title and subtitle
st.markdown('<div class="title">🎓 Student Performance Predictor</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Predict your academic performance based on key factors</div><br>', unsafe_allow_html=True)

# Two-column layout
col1, col2 = st.columns(2)

with col1:
    HS = st.slider("📚 Hours Studied per Day", 0, 12, 6)
    PS = st.slider("📝 Previous Scores", 0, 100, 70)
    EA = st.radio("🏅 Extracurricular Activities", ['Yes', 'No'], horizontal=True)

with col2:
    SH = st.slider("😴 Sleep Hours", 0, 12, 7)
    SQ = st.slider("📄 Sample Question Papers Practiced", 0, 10, 3)

# Convert EA to numeric
EA_val = 1 if EA == 'Yes' else 0

# Center the predict button
st.markdown("<br>", unsafe_allow_html=True)
centered_button = st.columns([1, 2, 1])[1]
with centered_button:
    if st.button("🚀 Predict Performance Index"):
        input_data = np.array([[HS, PS, SH, EA_val, SQ]])
        prediction = model.predict(input_data)
        st.success(f"🎯 Your Predicted Performance Index is: **{prediction[0]:.2f}**")

# Footer
st.markdown("<br><hr style='border: 1px solid #ccc'>", unsafe_allow_html=True)
st.markdown("<div style='text-align:center;'>Made with ❤️ using Streamlit</div>", unsafe_allow_html=True)
