# -*- coding: utf-8 -*-
"""student

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmhHp9aR_RI-ivXojj0x9khIp4aki6j4
"""



import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the model
def load_model():
    with open('stu.pkl', 'rb') as f:
        model = pickle.load(f)
    return model

model = load_model()

# Page configuration
st.set_page_config(page_title="Student Performance Predictor", layout="centered", page_icon="📊")

# Header
st.markdown("""
    <h1 style='text-align: center; color: #4B8BBE;'>🎓 Student Performance Predictor</h1>
    <p style='text-align: center; color: grey;'>Enter the student's academic details to predict their performance index.</p>
    <hr style='border: 1px solid #f0f0f0;'>
""", unsafe_allow_html=True)

# Input layout
col1, col2 = st.columns(2)

with col1:
    hours_studied = st.number_input("📘 Hours Studied", min_value=0.0, step=0.5)

with col2:
    prev_scores = st.number_input("📊 Previous Scores", min_value=0.0, step=1.0)

with col1:
    extracurricular = st.selectbox("🏀 Extracurricular Activities", ["Yes", "No"])
    ex = 1 if extracurricular.lower() == "yes" else 0

with col2:
    sleep_hours = st.number_input("😴 Sleep Hours", min_value=0.0, step=0.5)

with col1:
    sample_questions = st.number_input("📝 Sample Question Papers Practiced", min_value=0.0, step=1.0)

# Predict Button
if st.button("🔍 Predict Performance"):
    input_data = np.array([[hours_studied, prev_scores, sleep_hours, ex, sample_questions]])
    prediction = model.predict(input_data)

    st.success(f"🎯 Predicted Performance Index: **{prediction[0]:.2f}**")

    st.markdown("<hr style='border: 1px solid #f0f0f0;'>", unsafe_allow_html=True)

# Footer
st.markdown("""
    <div style='text-align: center; color: grey; font-size: 14px; margin-top: 40px;'>
        Developed by <strong>konjam_kadhalxx</strong> | Powered by Linear Regression 🔗
    </div>
""", unsafe_allow_html=True)
